version: '3'

services:
  server:
    depends_on:
      - db
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      DATABASE_URI: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
    restart: on-failure
    command: uvicorn main:app --host 0.0.0.0 --port ${SERVER_PORT:-8000}
    ports:
      - '8000:${SERVER_PORT:-8000}'
  db:
    image: postgres:alpine3.18
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasks
    ports:
      - '5432:${POSTGRES_PORT:-5432}'
    volumes:
      - postgres_data:/data/db
volumes:
  postgres_data:
    driver: local
