version: '3'

services:
  db_inventory:
    image: postgres:alpine3.18
    container_name: db_inventory
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory
    ports:
      - '5432:5432'
    volumes:
      - postgres_inventory_data:/data/db

  db_payment:
    image: postgres:alpine3.18
    container_name: db_payment
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payment
    ports:
      - '5433:5432'
    volumes:
      - postgres_payment_data:/data/db

volumes:
  postgres_inventory_data:
    driver: local

  postgres_payment_data:
    driver: local
