version: '3'
services:
  inventory:
    build:
      context: ./inventory
    ports:
      - "8000:8000"

  payment:
    build:
      context: ./payment
    ports:
      - "8001:8001"
    depends_on:
      - inventory
